name: Python Tests

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
      python-version:
        required: true
        type: string
    secrets:
      CODECOV_TOKEN:
        required: false

env:
  POETRY_VERSION: "1.8.4"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ inputs.python-version }} + Poetry ${{ env.POETRY_VERSION }}
        uses: "./.github/actions/poetry_setup"
        with:
          python-version: ${{ inputs.python-version }}
          poetry-version: ${{ env.POETRY_VERSION }}
          working-directory: ${{ inputs.working-directory }}
          cache-key: test

      - name: Install dependencies
        shell: bash
        run: |
          poetry install --with test
          # Install specific version of pydantic to ensure compatibility with langchain_core
          poetry run pip install "pydantic>=2.5.0"

      - name: Run tests
        if: inputs.working-directory == '.'
        shell: bash
        run: |
          # Remove asyncio_mode from pyproject.toml if it exists
          sed -i '/asyncio_mode/d' pyproject.toml
          # Run tests
          poetry run pytest -v

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ${{ inputs.working-directory }}
          fail_ci_if_error: false

      - name: Get minimum versions
        working-directory: ${{ inputs.working-directory }}
        id: min-version
        shell: bash
        run: |
          poetry run pip install packaging tomli requests
          python_version="$(poetry run python --version | awk '{print $2}')"
          min_versions="$(poetry run python $GITHUB_WORKSPACE/.github/scripts/get_min_versions.py pyproject.toml pull_request $python_version)"
          echo "min-versions=$min_versions" >> "$GITHUB_OUTPUT"
          echo "min-versions=$min_versions"

      - name: Run unit tests with minimum dependency versions
        if: ${{ steps.min-version.outputs.min-versions != '' }}
        env:
          MIN_VERSIONS: ${{ steps.min-version.outputs.min-versions }}
        run: |
          poetry run pip install uv
          poetry run uv pip install $MIN_VERSIONS
          # Install specific version of pydantic to ensure compatibility with langchain_core
          poetry run pip install "pydantic>=2.5.0"
          poetry run pytest

      - name: Ensure the tests did not create any additional files
        shell: bash
        run: |
          set -eu

          STATUS="$(git status)"
          echo "$STATUS"

          # grep will exit non-zero if the target message isn't found,
          # and `set -e` above will cause the step to fail.
          echo "$STATUS" | grep 'nothing to commit, working tree clean'
          
